sistema/config/routes.rb
Rails.application.routes.draw do
  resources :testes
  

  root 'testes#index'

  get 'ligar' => 'testes#ligar'
  get 'desligar' => 'testes#desligar'

end

sistema/app/models/teste.rb
class Teste < ActiveRecord::Base
end

sistema/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

sistema/app/controllers/testes_controller.rb
class TestesController < ApplicationController
  before_action :set_testis, only: [:show, :edit, :update, :destroy]

  # GET /testes
  # GET /testes.json
  def index
    @testes = Teste.all
  end


  def ligar
    #sudo apt-get install mpg123
    system('cd public && mpg123 -vC ligar.mp3')
    system('gpio mode 0 out')
    system('gpio -g write 17 1')
  end

  def desligar
    system('cd public && mpg123 -vC desligar.mp3')
    system('gpio mode 0 out')
    system('gpio -g write 17 0')
  end

  # GET /testes/1
  # GET /testes/1.json
  def show
  end

  # GET /testes/new
  def new
    @testis = Teste.new
  end

  # GET /testes/1/edit
  def edit
  end

  # POST /testes
  # POST /testes.json
  def create
    @testis = Teste.new(testis_params)

    respond_to do |format|
      if @testis.save
        format.html { redirect_to @testis, notice: 'Teste was successfully created.' }
        format.json { render :show, status: :created, location: @testis }
      else
        format.html { render :new }
        format.json { render json: @testis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testes/1
  # PATCH/PUT /testes/1.json
  def update
    respond_to do |format|
      if @testis.update(testis_params)
        format.html { redirect_to @testis, notice: 'Teste was successfully updated.' }
        format.json { render :show, status: :ok, location: @testis }
      else
        format.html { render :edit }
        format.json { render json: @testis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testes/1
  # DELETE /testes/1.json
  def destroy
    @testis.destroy
    respond_to do |format|
      format.html { redirect_to testes_url, notice: 'Teste was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testis
      @testis = Teste.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testis_params
      params[:testis]
    end
end

sistema/app/helpers/application_helper.rb
module ApplicationHelper
end

sistema/app/helpers/testes_helper.rb
module TestesHelper
end

sistema/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sistema</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<%= yield %>
		</div>
	</div>
</div>

</body>
</html>

sistema/app/views/testes/_form.html.erb
<%= form_for(@testis) do |f| %>
  <% if @testis.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testis.errors.count, "error") %> prohibited this testis from being saved:</h2>

      <ul>
      <% @testis.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

sistema/app/views/testes/desligar.html.erb
<center><%= link_to 'Ligar',ligar_path,:class => "btn btn-success btn-lg btn-block" %></center><br>
<center><%= link_to 'Desligar',desligar_path,:class => "btn btn-danger btn-lg btn-block" %></center>

sistema/app/views/testes/edit.html.erb
<h1>Editing testis</h1>

<%= render 'form' %>

<%= link_to 'Show', @testis %> |
<%= link_to 'Back', testes_path %>

sistema/app/views/testes/index.html.erb
<center><%= link_to 'Ligar',ligar_path,:class => "btn btn-success btn-lg btn-block" %></center><br>
<center><%= link_to 'Desligar',desligar_path,:class => "btn btn-danger btn-lg btn-block" %></center>

sistema/app/views/testes/ligar.html.erb
<center><%= link_to 'Ligar',ligar_path,:class => "btn btn-success btn-lg btn-block" %></center><br>
<center><%= link_to 'Desligar',desligar_path,:class => "btn btn-danger btn-lg btn-block" %></center>

sistema/app/views/testes/new.html.erb
<h1>New testis</h1>

<%= render 'form' %>

<%= link_to 'Back', testes_path %>

sistema/app/views/testes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_testis_path(@testis) %> |
<%= link_to 'Back', testes_path %>